name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
        contents: write
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env
        
      - name: Read NAME and VERSION from spec file
        id: spec
        run: |
          NAME=$(grep "^NAME" inventory_computostore.spec | cut -d"'" -f2)
          VERSION=$(grep "^VERSION" inventory_computostore.spec | cut -d"'" -f2)
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
            
      - name: Build executable
        run: pyinstaller inventory_computostore.spec

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/${{ env.NAME }}-${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "Nuevo release generado automáticamente con Github Actions."
          draft: false
          prerelease: false